### ISSUE TITLE
Require successful end-to-end (e2e) tests as a requirement for PR merge

### ISSUE THREAD

**Issue by arikkfir** [arikkfir/greenstar#23]
Sample workflow snippet:

```yaml
  e2e-tests:
    runs-on: ubuntu-22.04
    needs: deploy-to-environment
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: e2e/package-lock.json
      - run: |
          npm ci
          npx playwright install --with-deps
#          npx playwright test
        working-directory: e2e
```
